-- ============================================
-- Migration: Enrollments Table
-- Run after database_final.sql + profiles/courses exist
-- ============================================

create table if not exists enrollments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references profiles(id) on delete cascade,
  course_id bigint not null references courses(id) on delete cascade,
  created_at timestamptz default now(),
  unique(user_id, course_id)
);

alter table enrollments enable row level security;

create policy "Admin all enrollments"
  on enrollments for all
  using (public.is_admin())
  with check (public.is_admin());

create policy "Student own enrollments"
  on enrollments for select
  using (auth.uid() = user_id);

-- Seed: enroll all existing users in all courses
insert into enrollments (user_id, course_id)
select p.id, c.id from profiles p cross join courses c
on conflict do nothing;

-- Auto-enroll trigger: new user gets enrolled in all courses
create or replace function auto_enroll_new_user()
returns trigger as $$
begin
  insert into enrollments (user_id, course_id)
  select new.id, c.id from courses c
  on conflict do nothing;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_profile_created on profiles;
create trigger on_profile_created
  after insert on profiles
  for each row execute function auto_enroll_new_user();
