-- Image-based exam questions: question + options all in one image, student picks A/B/C/D
CREATE TABLE IF NOT EXISTS exam_image_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exam_id BIGINT NOT NULL REFERENCES exams(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  correct TEXT NOT NULL DEFAULT 'A',
  explanation TEXT DEFAULT '',
  sort_order BIGINT DEFAULT 0
);

ALTER TABLE exam_image_questions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can manage image questions"
  ON exam_image_questions FOR ALL
  TO authenticated
  USING ((SELECT role FROM profiles WHERE id = auth.uid()) = 'admin')
  WITH CHECK ((SELECT role FROM profiles WHERE id = auth.uid()) = 'admin');

CREATE POLICY "Students can read image questions"
  ON exam_image_questions FOR SELECT
  TO authenticated
  USING (true);

-- Image-based homework questions: same concept for homework
CREATE TABLE IF NOT EXISTS hw_image_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  homework_id BIGINT NOT NULL REFERENCES homework(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  correct TEXT NOT NULL DEFAULT 'A',
  explanation TEXT DEFAULT '',
  sort_order BIGINT DEFAULT 0
);

ALTER TABLE hw_image_questions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can manage hw image questions"
  ON hw_image_questions FOR ALL
  TO authenticated
  USING ((SELECT role FROM profiles WHERE id = auth.uid()) = 'admin')
  WITH CHECK ((SELECT role FROM profiles WHERE id = auth.uid()) = 'admin');

CREATE POLICY "Students can read hw image questions"
  ON hw_image_questions FOR SELECT
  TO authenticated
  USING (true);

-- Dynamic exam system: attempts, pools, final exam
ALTER TABLE exams ADD COLUMN IF NOT EXISTS total_questions BIGINT DEFAULT 0;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS max_attempts BIGINT DEFAULT 0;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS attempt_pass_score BIGINT DEFAULT 60;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS has_final_exam BOOLEAN DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS exam_student_pool (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  lesson_id BIGINT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
  question_type TEXT NOT NULL CHECK (question_type IN ('standard', 'image')),
  question_id BIGINT NOT NULL,
  seen BOOLEAN NOT NULL DEFAULT FALSE,
  attempt_id BIGINT,
  UNIQUE(user_id, lesson_id, question_type, question_id)
);

CREATE TABLE IF NOT EXISTS exam_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  lesson_id BIGINT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
  question_order JSONB,
  attempt_number INT NOT NULL,
  score INT NOT NULL DEFAULT 0,
  total INT NOT NULL DEFAULT 0,
  answers JSONB,
  passed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS final_exam_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  lesson_id BIGINT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
  score INT NOT NULL DEFAULT 0,
  total INT NOT NULL DEFAULT 0,
  answers JSONB,
  passed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE exam_attempts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can read own attempts" ON exam_attempts FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own attempts" ON exam_attempts FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own attempts" ON exam_attempts FOR UPDATE TO authenticated USING (auth.uid() = user_id);

ALTER TABLE exam_student_pool ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can read own pool" ON exam_student_pool FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own pool" ON exam_student_pool FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own pool" ON exam_student_pool FOR UPDATE TO authenticated USING (auth.uid() = user_id);

ALTER TABLE final_exam_attempts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can read own final exam" ON final_exam_attempts FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own final exam" ON final_exam_attempts FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own final exam" ON final_exam_attempts FOR UPDATE TO authenticated USING (auth.uid() = user_id);

CREATE POLICY "Admins can read all attempts" ON exam_attempts FOR SELECT TO authenticated USING ((SELECT role FROM profiles WHERE id = auth.uid()) = 'admin');
CREATE POLICY "Admins can read all pools" ON exam_student_pool FOR SELECT TO authenticated USING ((SELECT role FROM profiles WHERE id = auth.uid()) = 'admin');
