-- Device tracking for login limit (default 2 devices per user)
CREATE TABLE IF NOT EXISTS user_devices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  device_id TEXT NOT NULL,
  device_name TEXT DEFAULT '',
  ip_address TEXT DEFAULT '',
  last_login TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, device_id)
);
CREATE INDEX IF NOT EXISTS idx_user_devices_user ON user_devices(user_id);

-- Per-user device limit override (default 2)
CREATE TABLE IF NOT EXISTS user_device_limits (
  user_id UUID PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE,
  max_devices INT NOT NULL DEFAULT 2
);

-- Support tickets
CREATE TABLE IF NOT EXISTS support_tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  subject TEXT NOT NULL CHECK (char_length(subject) >= 3 AND char_length(subject) <= 200),
  message TEXT NOT NULL CHECK (char_length(message) <= 5000),
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'admin_replied', 'resolved', 'closed')),
  admin_reply TEXT DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_support_tickets_user ON support_tickets(user_id);
CREATE INDEX IF NOT EXISTS idx_support_tickets_status ON support_tickets(status);

-- ========== RLS: user_devices ==========
ALTER TABLE user_devices ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users_read_own_devices" ON user_devices
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "users_insert_own_devices" ON user_devices
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "users_delete_own_devices" ON user_devices
  FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "admins_read_all_devices" ON user_devices
  FOR SELECT USING ((SELECT role FROM profiles WHERE id = auth.uid()) IN ('admin', 'teacher'));

CREATE POLICY "admins_delete_any_device" ON user_devices
  FOR DELETE USING ((SELECT role FROM profiles WHERE id = auth.uid()) IN ('admin', 'teacher'));

-- ========== RLS: user_device_limits ==========
ALTER TABLE user_device_limits ENABLE ROW LEVEL SECURITY;

CREATE POLICY "admins_manage_device_limits" ON user_device_limits
  FOR ALL USING ((SELECT role FROM profiles WHERE id = auth.uid()) IN ('admin', 'teacher'));

CREATE POLICY "users_read_own_limit" ON user_device_limits
  FOR SELECT USING (auth.uid() = user_id);

-- ========== RLS: support_tickets ==========
ALTER TABLE support_tickets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users_insert_own_tickets" ON support_tickets
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "users_read_own_tickets" ON support_tickets
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "users_update_own_tickets" ON support_tickets
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id AND (status IN ('open','resolved')));

CREATE POLICY "admins_read_all_tickets" ON support_tickets
  FOR SELECT USING ((SELECT role FROM profiles WHERE id = auth.uid()) IN ('admin', 'teacher'));

CREATE POLICY "admins_update_tickets" ON support_tickets
  FOR UPDATE USING ((SELECT role FROM profiles WHERE id = auth.uid()) IN ('admin', 'teacher'));
